define({
	pedalSearchAmbiguousNameMessage: "Hmmm... Try a more specific name.",
	pedalSearchNoResultsMessage: "Oops! I couldn't find any pedals with that name.",
	pedalSearchNoInputMessage: "You have to search for something!",
	pedalSearchPlaceholder: "Search",
	deletePedalBoard: "Delete",
	addPedalToBoard: "Add Pedal",
	defaultPedalBoardName: "My Pedalboard",
	addPedalBoardButtonText: "Add Board",
	newBoardNamePlaceholder: "New Pedalboard Name",
	clearAllBoards: "Delete All",
	clearAllBoardsConfirm: "This will delete all pedalboards currently on the page. Are you sure?",
	singleBoardDeleteConfirm: "This will delete this pedalboard forever. Are you sure?",
	clearPedalsFromBoard: "Clear",
	clearPedalsFromBoardConfirm: "This will delete all of the pedals on this board. Are you sure?",
	saveBoardsToStorageButton: "Save",
	boardReportButton: "Report",
	boardCompareButton: "Compare",
	
	/* change log resources */
	change_AddBoard: "Added pedalboard \"{0}\"",
	change_RenamedBoard: "Renamed pedalboard \"{0}\" to \"{1}\"",
	change_DeleteBoard: "Deleted pedalboard \"{0}\"",
	change_DeleteAllBoards: "Deleted all pedalboards",
	change_AddPedal: "Added {0} to \"{1}\"",
	change_RemovedPedal: "Removed {0} from \"{1}\"",
	change_ClearedBoard: "Cleared all pedals from pedalboard \"{0}\"",
	change_ResizeBoard: "Resized pedalbard \"{0}\"",
	change_MoveBoard: "Moved pedalbard \"{0}\"",
	
	restoreBatchName: "Restored from save",
	pedalBoardDragHelpText: "Drag and drop to change order or delete",
});