define({
	pedalSearchAmbiguousNameMessage: "Hmmm... Try a more specific name.",
	pedalSearchNoResultsMessage: "Oops! I couldn't find any pedals with that name.",
	pedalSearchNoInputMessage: "You have to search for something!",
	pedalSearchPlaceholder: "Search",
	deletePedalBoard: "Delete",
	addPedalToBoard: "Add Pedal",
	defaultPedalBoardName: "My Pedalboard",
	addPedalBoardButtonText: "Add Board",
	newBoardNamePlaceholder: "New Pedalboard Name",
	clearAllBoards: "Delete All",
	clearAllBoardsConfirm: "This will delete all pedalboards currently on the page. Are you sure?",
	singleBoardDeleteConfirm: "This will delete this pedalboard forever. Are you sure?",
	clearPedalsFromBoard: "Clear",
	clearPedalsFromBoardConfirm: "This will delete all of the pedals on this board. Are you sure?",
	pedalBoardDragHelpText: "Drag and drop to change order or delete",
	historyPopupTitle: "History",
	pedalboardNoPedalsHelpText: "Add The First Pedal To This Board!",
	
	/* change log resources */
	change_AddBoard: "Created pedalboard \"{0}\"",
	change_RenamedBoard: "Renamed pedalboard \"{0}\" to \"{1}\"",
	change_DeleteBoard: "Deleted pedalboard \"{0}\"",
	change_DeleteAllBoards: "Deleted all pedalboards",
	change_AddPedal: "Added {0} to \"{1}\"",
	change_RemovedPedal: "Removed {0} from \"{1}\"",
	change_ClearedBoard: "Cleared all pedals from pedalboard \"{0}\"",
	change_ResizeBoard: "Resized pedalbard \"{0}\"",
	change_MoveBoard: "Moved pedalbard \"{0}\"",
	change_MovePedalUp: "Moved {0} up on pedalboard \"{1}\"",
	change_MovePedalDown: "Moved {0} down on pedalboard \"{1}\"",
	change_MovePedalToTop: "Moved {0} to the top of pedalboard \"{1}\"",
	change_MovePedalToBottom: "Moved {0} to the bottom of pedalboard \"{1}\"",
	firstStartupBatchName: "Let the games begin!",
	
	/*reporting*/
	boardReportButton: "Report",
	boardCompareButton: "Compare",
	compareToMenuHelpText: "To which board?",
	reportInWhatWayHelpText: "On what?",
	reportBoardDiffTitle: "{0} of pedals on \"{1}\" but not on \"{2}\"",
	reportBoardTitle: "{0} of pedals on \"{1}\"",
	reportTotalPedlas: "{0} pedals",
	reportType_Price: "Price",
	reportType_Diff: "Difference",
	reportType_PedalType: "Pedal Type",
	reportType_Color: "Color",
	color_DarkRed: "Dark Red",
	color_Red: "Red",
	color_Pink: "Pink",
	color_LightPurple: "Light Purple",
	color_Purple: "Purple",
	color_DarkBlue: "Dark Blue",
	color_Blue: "Blue",
	color_Turquoise: "Turquoise", 
	color_LightGreen: "Light Green",
	color_Green: "Green",
	color_DarkGreen: "Dark Green",
	color_YellowBrown: "Dejon Yellow",
	color_DarkYelow: "Dark Yellow",
	color_Yellow: "Yellow",
	color_LightYellow: "Light Yellow",
	color_LightOrange: "Light Orange",
	color_Orange: "Orange",
	color_DarkOrange: "Dark Orange",
	color_LightBrown: "Light Brown",
	color_Brown: "Brown",
	color_Black: "Black",
	color_Gray: "Gray",
	color_LightGray: "Light Gray",
	color_White: "White",
});