define({
			 notPedalsWithIdMessage: 'No pedals with that id are on this pedalboard.',
			 ambiguousNameMessage: "That name is ambiguous. Please be more specific.",
  		 noResultsMessage: "No pedals were found by that name.",
			 noInputMessage: "You have to search for something! Try typing above.",
			 save: "Save",
			 cancel: "Cancel",
			 addButtonText: "Add",
			 addPedal: "Add Pedal",
			 pedalSearchPlaceholder: "Search",
			 deletePedalBoard: "Delete",
			 addPedalToBoard: "Add Pedal",
			 defaultPedalBoardName: "My Pedalboard",
			 addPedalBoardButtonText: "Add Board",
			 newBoardNamePlaceholder: "New Pedalboard Name",
			 clearAllBoards: "Clear All",
			 clearAllBoardsConfirm: "This will delete all pedalboards currently on the page. Are you sure?",
			 singleBoardDeleteConfirm: "This will delete this pedalboard forever. Are you sure?",
});